kafka-acls:
  - action: "--add"
    allow-principal: "User:team1"
    operations:
      - "READ"
      - "DESCRIBE"
    topic: "mytopic"
    resource-pattern-type: "literal"

  - action: "--add"
    allow-principal: "User:team1"
    operations:
      - "READ"
      - "DESCRIBE"
      - "WRITE"
    topic: "mytopic1"
    resource-pattern-type: "prefixed"

  - action: "--add"
    allow-principal: "User:team2"
    operations:
      - "READ"
      - "DESCRIBE"
    group: "mygroup"
    resource-pattern-type: "literal"

  - action: "--add"
    allow-principal: "User:team2"
    operations:
      - "READ"
      - "DESCRIBE"
    group: "mygroup1"
    resource-pattern-type: "prefixed"