kafka-acls:
  - action: "--add"
    allow-principal: "User:team1"
    operations:
      - "WRITE"
      - "DESCRIBE"
    transactional-id: "team1-streams-app1"
    resource-pattern-type: "prefixed"

  - action: "--add"
    allow-principal: "User:team2"
    operations:
      - "WRITE"
      - "DESCRIBE"
    transactional-id: "team2-streams-app2"
    resource-pattern-type: "literal"