apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-acls-job
  namespace: confluent
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-acls
        image: confluentinc/cp-kafka:7.8.0
        command: ["/bin/bash", "-c"]
        args:
          - |
            cp /scripts/acl-script.sh /tmp/acl-script.sh &&
            chmod +x /tmp/acl-script.sh &&
            /scripts/acl-script.sh
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        - name: config-volume
          mountPath: /config
      volumes:
      - name: script-volume
        configMap:
          name: kafka-acls-script
      - name: config-volume
        configMap:
          name: kafka-acls-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-acls-script
  namespace: confluent
data:
  acl-script.sh: |
    #!/bin/bash
    set -e
    CONFIG_FILE="/config/acl-config.yaml"

    get_yaml_value() {
        local key=$1
        grep "^\s*$key:" "$CONFIG_FILE" | awk -F ': ' '{print $2}'
    }

    action=$(get_yaml_value "kafka-acls.action")
    principal=$(get_yaml_value "kafka-acls.allow-principal")
    transactional_id=$(get_yaml_value "kafka-acls.transactional-id")
    resource_pattern_type=$(get_yaml_value "kafka-acls.resource-pattern-type")
    operations=($(grep "^\s*-" "$CONFIG_FILE" | awk '{print $2}'))

    for operation in "${operations[@]}"; do
        if kafka-acls.sh --bootstrap-server <KAFKA_BROKER> --list --transactional-id "$transactional_id" | grep -q "$operation"; then
            echo "ACL for $operation on $transactional_id already exists. Skipping."
        else
            echo "Creating ACL for $operation on $transactional_id."
            kafka-acls.sh --bootstrap-server <KAFKA_BROKER> "$action" --allow-principal "$principal" \
                --operation "$operation" --transactional-id "$transactional_id" \
                --resource-pattern-type "$resource_pattern_type"
        fi
    done
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-acls-config
  namespace: confluent
data:
  acl-config.yaml: |
    kafka-acls:
      action: "--add"
      allow-principal: "User:team1"
      operations:
        - "WRITE"
        - "DESCRIBE"
      transactional-id: "team1-streams-app1"
      resource-pattern-type: "prefixed"
